from db.models.activity import DailyActivity
from db.models.attendance_learning import (
    AttendanceRecord,
    AttendanceSession,
    SemesterNorm,
    StudentTestAttempt,
    TheoreticalQuestion,
    TheoreticalTest,
)
from db.models.auth import User
from db.models.exercises import (
    Equipment,
    Exercise,
    ExerciseCategory,
    InjuryType,
    JTExerciseContraindication,
    JTExerciseEquipment,
    JTExerciseMuscleGroup,
    MuscleGroup,
    StudentInjuryHistory,
)
from db.models.enums import (
    AttendanceStatusEnum,
    CreditStatusEnum,
    DayOfWeekEnum,
    FatigueStatusEnum,
    GenderEnum,
    PerceivedDifficultyEnum,
    SatisfactionEnum,
    SlotTypeEnum,
    TestTypeEnum,
    UserRoleEnum,
    WorkoutStatusEnum,
)
from db.models.gamification import (
    Achievement,
    StudentAchievement,
    StudentRatingSnapshot,
)
from db.models.health import (
    AssessmentRule,
    AssessmentVersion,
    MedicalGroup,
    Student,
    StudentCreditStatus,
    StudentsHealthProfile,
    StudentsPhysicalReadinessAssessment,
)
from db.models.workout import (
    AssignedExercise,
    AssignedExerciseMuscleGroup,
    MuscleFatigue,
    StudentAssignedExerciseInteraction,
    WorkoutPlan,
    WorkoutStandard,
)

__all__ = [
    "Achievement",
    "AssessmentRule",
    "AssessmentVersion",
    "AssignedExercise",
    "AssignedExerciseMuscleGroup",
    "AttendanceRecord",
    "AttendanceSession",
    "AttendanceStatusEnum",
    "CreditStatusEnum",
    "DayOfWeekEnum",
    "DailyActivity",
    "Equipment",
    "Exercise",
    "ExerciseCategory",
    "FatigueStatusEnum",
    "GenderEnum",
    "InjuryType",
    "JTExerciseContraindication",
    "JTExerciseEquipment",
    "JTExerciseMuscleGroup",
    "MedicalGroup",
    "MuscleFatigue",
    "MuscleGroup",
    "PerceivedDifficultyEnum",
    "SatisfactionEnum",
    "SlotTypeEnum",
    "SemesterNorm",
    "Student",
    "StudentAchievement",
    "StudentAssignedExerciseInteraction",
    "StudentCreditStatus",
    "StudentInjuryHistory",
    "StudentRatingSnapshot",
    "StudentTestAttempt",
    "StudentsHealthProfile",
    "StudentsPhysicalReadinessAssessment",
    "TestTypeEnum",
    "TheoreticalQuestion",
    "TheoreticalTest",
    "User",
    "UserRoleEnum",
    "WorkoutPlan",
    "WorkoutStandard",
    "WorkoutStatusEnum",
]
