import React, { useState, useEffect, lazy, Suspense } from 'react';
import { useQuery } from '@tanstack/react-query';
import { LayoutDashboard, Dumbbell, HeartPulse, Users, Sparkles, LogOut, ArrowUpRight, Menu, Globe, ShieldCheck, Activity } from 'lucide-react';
import { api, fetcher, queryClient } from './api';
import { LocaleContext, Brand, Button, Field, Notice, Loading, ErrorMessage } from './components';
const Pages = lazy(() => import('./pages'));

export default function App() {
  const [language, setLanguage] = useState(localStorage.getItem('smartpe-language') || 'en');
  const [token, setToken] = useState(sessionStorage.getItem('smartpe-token'));
  const [page, setPage] = useState('overview');
  const [sid, setSid] = useState(null);
  const [menu, setMenu] = useState(false);
  const t = (en, ru) => language === 'ru' ? ru : en;
  const me = useQuery({ queryKey: ['me'], queryFn: fetcher('/auth/me'), enabled: !!token, retry: false });
  const logout = () => { sessionStorage.removeItem('smartpe-token'); sessionStorage.removeItem('smartpe-chat'); queryClient.clear(); setToken(null); setSid(null); setPage('overview'); };
  useEffect(() => { window.addEventListener('smartpe-expired', logout); return () => window.removeEventListener('smartpe-expired', logout); }, []);
  useEffect(() => { localStorage.setItem('smartpe-language', language); document.documentElement.lang = language; }, [language]);
  const changePage = next => { setPage(next); setMenu(false); };
  const teacher = me.data?.role === 'teacher';
  const navigation = [[ 'overview', LayoutDashboard, t('Overview', 'Обзор') ], ...(teacher ? [['students', Users, t('Students', 'Студенты')]] : []), ['workouts', Dumbbell, t('Workout plans', 'Тренировки')], ['health', HeartPulse, t('Health & recovery', 'Здоровье')], [teacher ? 'model' : 'chat', Sparkles, teacher ? t('AI model', 'Модель ИИ') : t('AI coach', 'ИИ-тренер')]];
  const languageButton = <button className="language-button" onClick={() => setLanguage(language === 'en' ? 'ru' : 'en')} aria-label={t('Switch to Russian', 'Переключить на английский')}><Globe size={16}/>{language === 'en' ? 'EN' : 'RU'}</button>;
  return <LocaleContext.Provider value={{ language, t }}>
    {!token ? <Login t={t} languageButton={languageButton} onLogin={result => { sessionStorage.setItem('smartpe-token', result.access_token); setToken(result.access_token); }}/>
      : me.isPending ? <main className="boot"><Brand/><Loading/></main>
      : me.isError ? <main className="boot"><ErrorMessage error={me.error} retry={me.refetch}/><Button onClick={logout}>{t('Back to sign in', 'Вернуться ко входу')}</Button></main>
      : <div className="app-shell"><aside className={`sidebar ${menu ? 'is-open' : ''}`}><Brand/><div className="workspace-label">{teacher ? t('TEACHER WORKSPACE', 'КАБИНЕТ ПРЕПОДАВАТЕЛЯ') : t('YOUR PERSONAL SPACE', 'ЛИЧНЫЙ КАБИНЕТ')}</div><nav>{navigation.map(([key, Icon, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => changePage(key)}><Icon size={19}/>{label}{page === key && <span className="nav-dot"/>}</button>)}</nav><div className="sidebar-note"><ShieldCheck size={25}/><strong>{t('Built around you', 'С учётом ваших возможностей')}</strong><p>{t('Personalized movement. Thoughtful recovery. A stronger you.', 'Персональные тренировки, восстановление и прогресс.')}</p></div><div className="account"><div className="avatar">{teacher ? 'T' : 'S'}</div><div><strong>{teacher ? t('Teacher', 'Преподаватель') : t('Student', 'Студент')}</strong><small title={me.data.email}>{me.data.email}</small></div><button className="icon-button" onClick={logout} aria-label={t('Sign out', 'Выйти')}><LogOut size={18}/></button></div></aside>
        {menu && <button className="mobile-overlay" aria-label={t('Close navigation', 'Закрыть меню')} onClick={() => setMenu(false)}/>}
        <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label={t('Open navigation', 'Открыть меню')} onClick={() => setMenu(!menu)}><Menu size={22}/></button><span className="breadcrumb">{t('Workspace', 'Кабинет')} <span>/</span> <strong>{navigation.find(item => item[0] === page)?.[2]}</strong></span></div><div className="topbar-right"><span className="today">{new Intl.DateTimeFormat(language === 'ru' ? 'ru-RU' : 'en-GB', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date())}</span>{languageButton}</div></header><main className="main-content"><Suspense fallback={<Loading/>}><Pages page={page} navigate={changePage} user={me.data} sid={teacher ? sid : me.data.student_id} selectStudent={id => { setSid(id); changePage('workouts'); }}/></Suspense></main><footer>Smart PE <span>•</span> {t('Every move matters.', 'Каждое движение имеет значение.')}</footer></div></div>}
  </LocaleContext.Provider>;
}

function Login({ t, onLogin, languageButton }) {
  const config = useQuery({ queryKey: ['/auth/config'], queryFn: fetcher('/auth/config'), retry: false });
  const [register, setRegister] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); const fields = Object.fromEntries(new FormData(event.currentTarget)); try { onLogin(await api(register ? '/auth/register' : '/auth/login', { method: 'POST', body: register ? { ...fields, student_id: Number(fields.student_id), role: 'student' } : fields })); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="login-page"><section className="login-story"><Brand light/><div className="story-content"><span className="pill"><span className="live-dot"/>{t('INTELLIGENT PHYSICAL EDUCATION', 'УМНАЯ ФИЗИЧЕСКАЯ КУЛЬТУРА')}</span><h1>{t('Your next move.', 'Ваш следующий шаг.')}<br/><em>{t('Made for you.', 'На пути к себе.')}</em></h1><p>{t('Training that understands your strengths, respects your limits, and grows with you.', 'Тренировки, которые учитывают ваши возможности, поддерживают здоровье и меняются вместе с вами.')}</p><div className="orbit-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit-core"><Activity size={68}/></div><div className="floating-chip"><Sparkles size={18}/>{t('Personalized by AI', 'Персонализация с ИИ')}</div><div className="floating-score"><HeartPulse size={22}/><div><strong>{t('A balanced approach', 'Баланс нагрузки')}</strong><span>{t('Movement + recovery', 'Движение + восстановление')}</span></div></div></div></div><div className="story-footer">{t('MOVE WITH PURPOSE. GROW AT YOUR PACE.', 'ДВИЖЕНИЕ СО СМЫСЛОМ. ПРОГРЕСС В ВАШЕМ ТЕМПЕ.')}</div></section><section className="login-panel"><div className="login-language">{languageButton}</div><form className="login-form" onSubmit={submit}><span className="eyebrow">{t('WELCOME TO SMART PE', 'ДОБРО ПОЖАЛОВАТЬ В SMART PE')}</span><h2>{register ? t('Create your account', 'Создайте аккаунт') : t('Good to see you.', 'Рады вас видеть.')}</h2><p>{register ? t('Connect to your existing student profile.', 'Подключитесь к своему профилю студента.') : t('Sign in to continue your fitness journey.', 'Войдите, чтобы продолжить путь к вашим целям.')}</p><Field label={t('Email address', 'Электронная почта')} type="email" name="email" autoComplete="username" placeholder="you@university.edu" required/><Field label={t('Password', 'Пароль')} type="password" name="password" autoComplete={register ? 'new-password' : 'current-password'} minLength={register ? 8 : undefined} required/>{register && <Field label={t('Student ID (provided by your teacher)', 'ID студента (у преподавателя)')} type="number" name="student_id" min="1" required/>}{error && <Notice>{error}</Notice>}<Button busy={busy} icon={ArrowUpRight} className="full-width">{register ? t('Create account', 'Создать аккаунт') : t('Sign in', 'Войти')}</Button>{config.data?.registration_enabled && <button type="button" className="text-link login-toggle" onClick={() => { setRegister(!register); setError(''); }}>{register ? t('Already registered? Sign in', 'Уже есть аккаунт? Войти') : t('New student? Create an account', 'Новый студент? Создать аккаунт')}</button>}<div className="login-security"><ShieldCheck size={16}/>{t('Your health data stays in your personal workspace.', 'Данные о здоровье доступны в вашем личном кабинете.')}</div></form></section></div>;
}
